### ISSUE TITLE
fitting does not work due to Yc array shape mismatch

### ISSUE THREAD

**Issue by tanmoylaskar** [georgeamccarthy/ykn#2]
https://github.com/georgeamccarthy/ykn/blob/57885009ee1149f356ce3ebb8d2a520d8ee78a78/ykn.py#L120

----> 1 grb1.fit()

~/Projects/GAMMA/grb.py in fit(self)
   2590 
   2591             fitcoefs,fittedfunc,iters,imode,smode = fmin_slsqp(lambda par_vary: grbfitter.minimizeme(par_vary, paramarray, vary_ind, fixed_ind, fixed_val, self.data, currentmodel, self.maskgrid, applyIC, applyKN)['minusLogL'], paramarray[vary_ind],\
-> 2592                         bounds=allbounds[vary_ind],full_output = 1, acc = 1e-3, iprint=2,iter=1000)
   2593 
   2594             newparamarray            = paramarray

~/Projects/GAMMA/slsqp.py in fmin_slsqp(func, x0, eqcons, f_eqcons, ieqcons, f_ieqcons, bounds, fprime, fprime_eqcons, fprime_ieqcons, args, iter, acc, iprint, disp, full_output, epsilon, callback)
    285 
    286     res = _minimize_slsqp(func, x0, args, jac=fprime, bounds=bounds,
--> 287                           constraints=cons, **opts)
    288     if full_output:
    289         return res['x'], res['fun'], res['nit'], res['status'], res['message']

~/Projects/GAMMA/slsqp.py in _minimize_slsqp(func, x0, args, jac, bounds, constraints, maxiter, ftol, iprint, disp, eps, callback, **unknown_options)
    476 
    477             # Compute objective function
--> 478             fx = func(x)
    479             try:
    480                 fx = float(np.asarray(fx))

~/Projects/GAMMA/slsqp.py in function_wrapper(*wrapper_args)
     97     def function_wrapper(*wrapper_args):
     98         ncalls[0] += 1
---> 99         return function(*(wrapper_args + args))
    100 
    101     return ncalls, function_wrapper

~/Projects/GAMMA/grb.py in <lambda>(par_vary)
   2589             ndim = len(vary_ind)
   2590 
-> 2591             fitcoefs,fittedfunc,iters,imode,smode = fmin_slsqp(lambda par_vary: grbfitter.minimizeme(par_vary, paramarray, vary_ind, fixed_ind, fixed_val, self.data, currentmodel, self.maskgrid, applyIC, applyKN)['minusLogL'], paramarray[vary_ind],\
   2592                         bounds=allbounds[vary_ind],full_output = 1, acc = 1e-3, iprint=2,iter=1000)
   2593 

~/Projects/GAMMA/grbfitter.py in minimizeme(par_vary, paramarray, vary_ind, fixed_ind, fixed_val, data, model, maskgrid, applyIC, applyKN, diagnostic)
     88     try:
     89         np.seterr(divide='raise',invalid='raise')
---> 90         modelflux_grid = model.getdatamodel(maskgrid)
     91         modelflux      = modelflux_grid[maskgrid]
     92     except FloatingPointError:

~/Projects/GAMMA/grb.py in getdatamodel(self, maskgrid)
   1792             modelflux = realspectra.fluxes(f = self.datamodel.freqgrid, params = self.params, hostfluxes = self.hostflux.fluxes, t = self.datamodel.timegrid, \
   1793                                            extcor_g = extcor_g, extcor_h = extcor_h, pabscor_g = pabscor_g, pabscor_h = pabscor_h, igmtrans = igmtrans, galtrans = galtrans,\
-> 1794                                            filtergrid = supplied_filtergrid, printweights = False)            
   1795 
   1796         if ((np.NaN in modelflux) or (np.inf in modelflux) or (np.NINF in modelflux)):

~/Projects/GAMMA/realspectra.py in fluxes(f, params, hostfluxes, t, extcor_g, extcor_h, pabscor_g, pabscor_h, igmtrans, galtrans, filtergrid, printweights)
   1001 
   1002     import numpy as np
-> 1003     modelgrid = spectrum(f, params, t, printweights)
   1004 
   1005     if (filtergrid is None):

~/Projects/GAMMA/realspectra.py in spectrum(f, params, t, printweights)
   1165     # Yc is calculated once here and then passed down through the functions to
   1166     # avoid recalculating.
-> 1167     Yc = gstable2.get_yc(params, t)
   1168 
   1169     edges_calc = edges(params)

~/Projects/GAMMA/gstable2.py in get_yc(params, t, Yc_calctype, coolingtype)
    426             gamma_self = get_gamma_self(params, t)
    427 
--> 428             return ykn.yc_approx(params, gammam, gammacs, gamma_self, YT=YT)
    429 
    430             """fast = gammam < gammac

~/Projects/GAMMA/ykn/ykn.py in yc_approx(params, gammam, gammacs, gamma_self, YT, debug)
    118 
    119     # Compute Yc in each functional regime.
--> 120     Yc[0] = YT
    121     Yc[1] = YT ** 2 * (gammacs / gammamhat) ** -1
    122     # Alternate equation

ValueError: could not broadcast input array from shape (52,10) into shape (52)

@georgeamccarthy

**Comment by georgeamccarthy** [comment]
Fixed, see https://github.com/georgeamccarthy/ykn/commit/e6a68a8ab1f51caedb587df88040f2c9c5546017
